### ISSUE TITLE
Useless Hints

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#111]
Hints such as Twillen's Bow/Bash hint grow useless eventually when you find all key items they reference.

This would be most intuitively handled by locking the purchase once you aquire the last needed part. To avoid unintuitive interferences with the shop-based bingo goal, these hint types should maybe not count for bingo goals

**Comment by toadettexmushina** [comment]
such hints can now be bought for 0 SL if needed

**Comment by SiriusAshling** [comment]
Reopening because we may still want this solution as a more intuitive approach

**Comment by toadettexmushina** [comment]
sorry, didn't mean to close it, just comment, whoops

**Comment by MunWolf** [comment]
personally I dont really mind having them as goals and costing 0 SL

**Comment by MunWolf** [comment]
Closing this as I don't think we are going to change it.
