### ISSUE TITLE
Patch 3 Kwolok Escape

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#117]
Since patch 3 of the vanilla game, the speed of Kwolok during the pre-battle chase sequence is broken.
This includes difficulty scaling (supposed to be slower on easy and faster on hard) as well as rubberbanding (slowing down when close to the player or catching up).
Neither of these have any effect, instead Kwolok moves at a predetermined speed.

This is an issue in general since it removes the intended lenience, but also specifically in the randomizer because it greatly limits the skillsets that can survive the chase - additionally the abilities required (mostly Dash/Grenadebash) are not hinted and commonly lock the player out of completion, which feels especially bad since it's the consequence of a bug.

Check patch 2 for the correct behaviour.

**Comment by MunWolf** [comment]
This was fixed a while ago.
