### ISSUE TITLE
Some TPs do no sync in co-op

### ISSUE THREAD

**Issue by timoschwarzer** [ori-rando/wotw-client#126]
TPs that I noticed not getting synced:

- Kwolok's Hollow
- Willow's End (both)

**Comment by Foopyo** [comment]
The one at the end of Willow's End isn't getting synced either

**Comment by MunWolf** [comment]
When me and Zre tried it they were syncing, so we are going to need some logs for this issue.

**Comment by MunWolf** [comment]
Should be fixed a while back.
