### ISSUE TITLE
Shop description texts

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#174]
Add a shop command to set the description of a shop item to be used on load

**Comment by MunWolf** [comment]
C++ currently has full support for this
`InterOp.Shop.set_opher_item(i, 255, pickup.ShopName, pickup.DescOrChatter(), s.Texture, lockedTillGlades, pickup is Ability a && costsEnergy.Contains(a.type));`
is one of the relevant methods and as you can see it passes DescOrChatter, chatter is the random text and Desc is only called when the pickup is a vanilla WeaponUpgrade.

**Comment by SiriusAshling** [comment]
There's already a shopcommand pickup for icons would make sense to expand on that for description texts.
Might even be nice to have one for the main display name in a shop? Currently headers use a workaround to create differing display texts and actual texts (e.g. "Black Market Keystone" and when you buy it just "Keystone")

**Comment by MunWolf** [comment]
How do we want to do chatter text?
Have some sort of special replacement text or a ChatterDescription shop command?

**Comment by MunWolf** [comment]
Added in https://github.com/ori-rando/wotw-client/commit/b5a841ce2295a9bea536d3d617df597a91d34d8b
