### ISSUE TITLE
Rapid Regenerate

### ISSUE THREAD

**Issue by toadettexmushina** [ori-rando/wotw-client#175]
speed healing - sphealing if you will XD

**Comment by timoschwarzer** [comment]
maybe even make this use all available energy to heal to max. health at once.

**Comment by toadettexmushina** [comment]
I dunno, there are times when you want to save some energy for other things. I think just speeding up the existing animation would be cool though, since it's long enough you have to stop and make yourself a target. Not as bad as hollow knight at least tho orilol

**Comment by timoschwarzer** [comment]
Shape of Unn pog

**Comment by toadettexmushina** [comment]
turn ori into a slime and wiggle around while saving

**Comment by timoschwarzer** [comment]
BIG YES

**Comment by toadettexmushina** [comment]
Bonus+ possible additions #290
