### ISSUE TITLE
uberState for eyestone statue

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#186]
Currently there is a syscommand (4|7) that toggles whether the player can interact with the eyestone statue.
This seems at odds with our usual design patterns, it should be a custom boolean uberState instead.

**Comment by MunWolf** [comment]
https://github.com/ori-rando/wotw-client/commit/323ef3a6ad203118439623980bd7757f8296592b does the fix on the client side

**Comment by SiriusAshling** [comment]
Is there backwards compability to toggle the uberState when using the command?

**Comment by MunWolf** [comment]
Nope, did the same thing as the other ones did.
Print a depracated message oriLol

**Comment by MunWolf** [comment]
(I can add it in easily if you prefer that approach)
