### ISSUE TITLE
Expose player inventory resources

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#202]
Through system commands and pickups there is indirect access to add, subtract or set most resources (although still sometimes in rather limited ways)
Still missing is the ability to read them (e.g. compare in ifs or reference in a pointer)

We might want at least readable uberStates for the resources to solve that, or if possible writable ones that can replace the current system of commands and provide a less limiting environment to manipulate them.

Resources in this sense are: Spirit Light, Max Health, Current Health, Max Energy, Current Energy, Gorlek Ore, Keystones

**Comment by MunWolf** [comment]
This has been done, look in /projects/InjectDLL/uber_states/uber_state_virtual.cpp for the relevant values.  (Note these do not show in the debug menu as they do not exist in the internal uberstate collection)

**Comment by SiriusAshling** [comment]
Added that file to the documentation (I imagine it's a bit hard to read though)
