### ISSUE TITLE
Logic Filter doesn't update on uberState changes

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#208]
namely uberState changes that appear in state_data.csv.
Since those are relevant for the reach check it can cause pickups to not show up in the logic filter until you Alt+L or collect a pickup etc.

**Comment by MunWolf** [comment]
Perhaps this was caused by https://github.com/ori-rando/wotw-client/issues/252 ?

**Comment by SiriusAshling** [comment]
No, I can still reproduce

**Comment by MunWolf** [comment]
hmm ok, guess we need to also check the state csv for states we should update the reach check on.
