### ISSUE TITLE
Logic Filter using current instead of total resources

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#224]
For the reach reach used by the in logic filter, the client sends the players current Gorlek Ore and Spirit Light.
This is incorrect, since those resources can be spent, but the logic is based on the total amount collected throughout the seed.

In consequence, e.g. after spending Spirit Light shops will disappear from the map, or after spending Gorlek Ore build-locked pickups will.

Keystones are already handled correctly, using the total amount aquired in the seed, but Ore and Spirit Light are not.

**Comment by MunWolf** [comment]
Wouldn't be better to keep the logic for gorlek ore as is, but add the states for build-locked pickups? So if you have bought thorns it shows the pickups locked by that as in logic even if seed gen would technically not consider it as logical.

It feels weird play pattern wise if you have bought thorns but they don't show up on the map.

For spirit light I don't mind changing to total.

**Comment by SiriusAshling** [comment]
All states the player already completed are considered for the logic filter, thorns and other buildings not showing up is a bug ( #252 ).

That does not solve this issue though. At generation time it is the total amount of gorlek ore that matters, if the logic filter does not comply to this at runtime it will cause incorrect results. To visualize it through an example:

Context: The second huts require finding a total of 21 Gorlek Ore.
The example player is a beginner, using the logic filter heavily to progress. They reach Glades with just 4 Ore and build the first hut, then collecting all the pickups unlocked by them (once above bug is fixed they will show in the logic map).
The go ahead and full clear the logic filter, until they have found a total of 21 Gorlek Ore.
The next progression is behind the second huts, however due to the bug described in this issue, that progression does not show on the logic map - they currently only own 17 Ore (even though that should be completely irrelevant to logic).
The logic filter at this point is completely empty - something we always want to avoid.

**Comment by SiriusAshling** [comment]
I checked since I recall this being fixed, this commit probably just forgot to link this issue?
https://github.com/ori-rando/wotw-client/commit/8a48ad4f6879aeabd3b4e8971d13791dc5e05a78

**Comment by MunWolf** [comment]
Probably oriLol, guess we can close it.
