### ISSUE TITLE
Inputlocked after launch

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#228]
Sometimes when launching the game, it gets stuck on the main menu screen without recognizing any inputs.

This seems to be related to unfocusing the window in a certain way, not sure on the details.

Supposedly this can happen in the vanilla game, but I never observed this myself.
Differences I could observe in the launch process of the vanilla game: The vanilla game pauses when unfocused (the randomizer prevents this as a qol feature) and the vanilla game force focuses the game on a certain step of the initial load before going to the main menu, the randomizer doesn't seem to be doing this.

**Comment by timoschwarzer** [comment]
This happens if you alt-tab out of the loading screen in a certain time span. This is vanilla behavior. You probably just alt-tab out of the loading screen more often in rando (to set up things etc) hence you'll experience it there more often.

**Comment by SiriusAshling** [comment]
This being vanilla behaviour does not seem to be correct, and it impacts new players as well as old ones.
Would prefer to keep this open as it's one of our more relevant/annoying bugs.

We don't seem to know the exact reproduction, would be good to find out that information

**Comment by SiriusAshling** [comment]
An additional piece of information:
The game does not get stuck in this inputlocked state immediately - you can progress through the "Press Any Key" screen, it then gets stuck on the "Start Game" etc. screen

**Comment by MunWolf** [comment]
Do we have a way to 100% reproduce this?
I know it happens when you alt-tab at a certain point but need a solid reproduction to nail down what is causing this (if it is a rando issue)

**Comment by timoschwarzer** [comment]
I tried to find a repro but failed to do so... :(

**Comment by MunWolf** [comment]
I would really like to bisect this but until I get a 100% reproducibly case of this I don't think I can find the root of this issue :/

**Comment by SiriusAshling** [comment]
Depending on the nature of the bug there's no guarantee that a reliable reproduction exists.
I get it every now and then though, if there's anything particular you'd be interested to check in the bugged state.

**Comment by SiriusAshling** [comment]
Did this get fixed at some point? Can't remember when it last happened

**Comment by timoschwarzer** [comment]
Yes it did.
