### ISSUE TITLE
Worl tour breaking logic filter in beta 1.1.0-17

### ISSUE THREAD

**Issue by Foopyo** [ori-rando/wotw-client#231]
When generating a seed with the World Tour goal mode, the logic filter won't work.

The issue is coming from the config JSON line at the end of a seed file: having the percentage of chance for a relic to spawn in one area specified in the goalmodes object of this json is breaking logic filter.

It's easily reproductable:
1) generate a world tour seed (no other options has to be selected)
2) start a new save file, open the logic filter which shouldn't work
3) open the seed file and remove `{"Relics":0.6}` from the `goalmodes` array
4) reload the seed and create a new save file
5) open the logic filter which should be working

**Comment by SiriusAshling** [comment]
This is due to the server that the interface communicates with being on a different version than your local seedgen, will fix itself on server update/non-beta release.

Using your local seedgen (currently only possible through the command line) with the steps above will not reproduce the issue.
