### ISSUE TITLE
Energy cost uberstate

### ISSUE THREAD

**Issue by Foopyo** [ori-rando/wotw-client#245]
Add an uberstate which would allow you to change:

- [ ] The amount of energy spend when using a weapon
- [ ] The amount of energy logic expects you to spend when using a weapon

**Comment by timoschwarzer** [comment]
The first one is already implemented. (The "efficiency" uber states)

**Comment by SiriusAshling** [comment]
The client is part is already implemented, the seedgen part is tracked on the seedgen repository, closing in favour of https://github.com/ori-rando/wotw-seedgen/issues/27
