### ISSUE TITLE
What is SysMessageType.ListHint?

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#246]
https://github.com/ori-rando/wotw-client/blob/e9a410967a1db8226cfbd37a4c9d030747eec547/projects/RandoMainDLL/Pickup.cs#L149

This isn't part of the documentation, what does it do?
Stumbled across it in https://github.com/ori-rando/wotw-client/blob/e9a410967a1db8226cfbd37a4c9d030747eec547/projects/RandoMainDLL/MapController.cs#L21 where such a listhint pickup is hidden from the logic filter (which also seems weird? Some players may play only on the logic filter, unchecked reachable locations shouldn't generally be hidden from them?)

**Comment by timoschwarzer** [comment]
According to git blame, it is a "location-list hint". I think it's the hints sold in shops.

**Comment by sparkle-preference** [comment]
it's deprecated and can be deleted.

**Comment by SiriusAshling** [comment]
(It was not in fact deprecated) oriLol

**Comment by SiriusAshling** [comment]
Creating documentation for it now

**Comment by SiriusAshling** [comment]
Done

**Comment by sparkle-preference** [comment]
oh my god i'm so sorry I was thinking of a different kind of hint @_@

**Comment by timoschwarzer** [comment]
all fine eiko Sirius did a fix fix :)
