### ISSUE TITLE
What is BonusType.HintOne?

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#251]
Time for round two! oriLol

BonusType has the two variant "HintOne" and "HintTwo" which are undocumented.
Source: https://github.com/ori-rando/wotw-client/blob/ecbb03d7e3bed9e73ac4dc7075294968b21c8a54/projects/RandoMainDLL/BonusItemController.cs#L8
Commit: https://github.com/ori-rando/wotw-client/commit/96a1cf6a638d38276870d6c354c77d9109ae70e6
Item codes: `10|10` and `10|11`

It doesn't seem like they are referenced in the csharp code or used in headers?

**Comment by MunWolf** [comment]
The bonus type values should correspond to the group 4 uberstate they change
in which case 10 and 11 are flat out wrong since they are now the bow and spear multiplier.

Personally think all of the bonus item code should be purged and moved ino headers (except maybe relics)

**Comment by timoschwarzer** [comment]
![image](https://user-images.githubusercontent.com/8849554/152630546-0eb1cf77-5936-460a-bbcc-3a152f16df4d.png)

seems like it
