### ISSUE TITLE
Skill naming consistency

### ISSUE THREAD

**Issue by toadettexmushina** [ori-rando/wotw-client#263]
Choose a specific name for each of the skills and consistently use that for the skill and its upgrades.
The base game has some "interesting" names for some of the skills, so it makes sense to use more commonly used names/descriptors. 

Current ability and upgrade names

_Spirit Edge / **Sword**_
 - Rapid Sword - Sword attacks are 25% faster
 - Melting Sword
 
_Spirit Arc / **Bow**_
 - Bow Efficiency - Spirit Arc costs 50% less energy
 - Quickshot Upgrade

_**Spike** / Spear_ 
 - Spike Efficiency - Spike costs 50% less energy
 - Exploding Spike - Spike explodes on hit
 - Rapid Spear

_Spirit Smash / **Hammer**_
 - Shock Smash - Drop attacks with Hammer create a shockwave
 - Rapid Smash - Hammer attacks are 25% faster

_Spirit Star / **Shuriken**_
 - Star Efficiency - Shuriken costs 50% less energy
 - Static Star - Tap to pause the Shuriken's flight and spin it in place
 - Melting Shuriken

_**Light Burst** / Grenade_
 - Grenade Efficiency - Grenade costs 50% less energy
 - Uncharged Bashgrenades
 - Extra Grenade
 - Splinter Grenade
 - Rapid Grenade

**_Regenerate_**
 - Regen Efficiency - Regenerate costs 50% less energy

Flap, Blaze, Flash, Sentry, Launch all have consistent upgrade names

**Comment by toadettexmushina** [comment]
My thoughts: 

I prefer Spear over Spike, it's clearer. Although it's not a huge deal, spikes as in the things you damage boost through are a thing, so there's some term overlap.

We call literally everything but the skill itself Grenade rather than Light Burst, I think that's rather telling.

Probably update the Bow Efficiency description

Shuriken Efficiency would be better. Static Star does sound better than Static Shuriken tho...

Shock Smash sounds cooler than Shock Hammer, so I think these might be ok.

**Comment by SiriusAshling** [comment]
Hmmm sometimes they're the game's canonical names and other times the terms developed in the speedrunning community.
Maybe vanilla names would be the better route though? Not every player comes from a speedrunning context.

**Comment by MunWolf** [comment]
Changing Static Shuriken and Shock Smash won't be happening as these are the original vanilla names.
My 2 cents would be to change everything to use the vanilla name.

**Comment by SiriusAshling** [comment]
Ok yeah lets not uncharged bash light burst lmao

**Comment by SiriusAshling** [comment]
Maybe some amount of inconsistency is fine.
I'd prefer not to rename the Opher upgrades, they have good names. Shock Smash? - oriDrool; Shock Hammer... not so much.

**Comment by toadettexmushina** [comment]
I guess I'll just lay out the changes I think would be good then. Some inconsistency is ok, especially when it comes to the vanilla upgrades - they sounds cool as is.

Bow Efficiency -  ̶S̶p̶i̶r̶i̶t̶ ̶A̶r̶c̶ Bow costs 50% less energy
 ̶S̶t̶a̶r̶ Shuriken Efficiency
 ̶L̶i̶g̶h̶t̶ ̶B̶u̶r̶s̶t̶ - Grenade
 ̶R̶e̶g̶e̶n̶ Regenerate Efficiency
 ̶S̶p̶i̶k̶e̶ Spear (same for all its upgrades)

**Comment by SiriusAshling** [comment]
Seems good

(github uses markdown btw, assuming that was supposed to be strikethrough you can do it similarly to discord:
`~Spirit Arc~` becomes ~Spirit Arc~

**Comment by toadettexmushina** [comment]
Made a pull request
