### ISSUE TITLE
Twillen's price isn't updating until you close the shop

### ISSUE THREAD

**Issue by Foopyo** [ori-rando/wotw-client#268]
Same issue as the Black Market Keystone back in the days: if you change the price of an item on Twillen shop, the text will update but the actual cost of the item won't be modified until you close the shop.

You can test this by using the Black Market Ore
[ores_black_market.zip](https://github.com/ori-rando/wotw-client/files/8116751/ores_black_market.zip)

**Comment by MunWolf** [comment]
Should be fixed on latest now
