### ISSUE TITLE
Logic Filter Transparency

### ISSUE THREAD

**Issue by FloSH02** [ori-rando/wotw-client#271]
While showing all "in-logic" pickups with 100% opacity, it would be great to see "out-of-logic" pickups semi-transparent.
this way you still can use the in-logic filter to see where logic wants to take you, but also see which pickups there are near you.

**Comment by FloSH02** [comment]
While showing all "in-logic" pickups with 100% opacity, it would be great to see "out-of-logic" pickups semi-transparent.
this way you still can use the in-logic filter to see where logic wants to take you, but also see which pickups there are near you.

**Comment by MunWolf** [comment]
Closed in https://github.com/ori-rando/wotw-client/commit/46f36b0534d02a4fbeba73ecf46550277be83048
