### ISSUE TITLE
Item name without coloring

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#281]
### Issue

Currently header such as [key hints](https://github.com/ori-rando/wotw-seedgen/blob/0f1269cc43e9adb8a5c5ee2524e718d8b2a0ec02/headers/key_hints.wotwrh) mention the item names literally, for instance:
`...|6|Burrow: $WHEREIS(2\|101), <\>`
It would be more flexible to rely on the client to interpret these names, such as through the `$[<item>]` syntax:
`...|6|$[2|101]: $WHEREIS(2\|101), <\>`
However, currently this has a drawback because the item name will be colored, which does not fit very well into the hint message. In this case it would evaluate to:
`...|6|*Burrow*: $WHEREIS(2\|101), <\>`
which is especially weird if that part of the hint is supposed to be colored green to signal the item has already been found.

### Proposal

A possible solution to this could be the proposed syntax: `$[<item>:nocolor]` (I think a similar syntax has been introduced for formatting during credits messages?)
This could strip all `$`, `@`, `#` and `*` characters from the item name to get the "uncolored" counterpart. For instance:
`...|6|$[2|101:nocolor]: $WHEREIS(2\|101), <\>`
should resolve to
`...|6|Burrow: $WHEREIS(2\|101), <\>`

### Motivation

Name as the original `$[<item>]` syntax really. Headers could refer to items in a way that will stay correct if we change any item names. Additionally this could be utilized for further header tools, such as inserting the user's custom item name if given, and only use the client name as a default if not.

**Comment by MunWolf** [comment]
@SiriusAshling This can be closed right? Just some work on the header/seedgen side?

**Comment by SiriusAshling** [comment]
I think it's still untested oriLol
But yeah should be implemented
