### ISSUE TITLE
Incorrectly rendered icons in spoiler filter

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#283]
Seed used: [seed_5789.zip](https://github.com/ori-rando/wotw-client/files/8391029/seed_5789.zip)

Various icons are rendered incorrectly in the spoiler filter. Examples:
- Double Jump Tree (wrong experience icon)
![image](https://user-images.githubusercontent.com/53594055/161098783-a6dfc77f-d4e2-4671-886f-6fc06574b993.png)
- First Pickup (incorrect orange particles)
![image](https://user-images.githubusercontent.com/53594055/161098945-f6933d58-05c6-4e3c-b018-670cb540fd2f.png)
- Below Opher experience (correctly rendered keystone for comparison)
![image](https://user-images.githubusercontent.com/53594055/161099218-5ee9ab8b-43f2-44fc-a7f6-f351bfa0ba23.png)
- Library Experience (correctly rendered spirit well for comparison)
![image](https://user-images.githubusercontent.com/53594055/161099398-4f65644a-fa8a-4d79-9c46-96b071a7a32d.png)
...and more different "thickly rendered" icons

**Comment by timoschwarzer** [comment]
IIRC the experience orbs don't have different textures on the map but differentiate by having different color modulation, with > 1 values. When we change the icon, that shader still affects the icon leading to this result.

**Comment by MunWolf** [comment]
Looks like its fixed in 2.0
