### ISSUE TITLE
Switching map filters while displaying labels leads to rendering issues

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#285]
When switching between the "All" and "In-Logic" filters while having labels displayed, it seems like labels get instantiated multiple times making them seem brighter (upper one is normal):
![image](https://user-images.githubusercontent.com/53594055/161101083-2e0ec500-0ff4-4a30-a35f-29e6a7e3da50.png)

When switching from "Spoilers" to "All" while having labels displayed, the icons get rendered incorrectly (I guess Glades is a ghost town now? oriThump):
![image](https://user-images.githubusercontent.com/53594055/161101356-314faa2f-d6d4-40f0-8b91-ef492f350d6a.png)

**Comment by MunWolf** [comment]
The text thing seems to only happen for Spirit Light it seems, still investigating.
