### ISSUE TITLE
Setting uberState don't get set correctly

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#286]
The "Show transparent icons" and "Disable always showing scecret areas" settings have no effect.

They get set correctly in the settings.ini file, however their corresponding uberStates (7|1000 and 4|38) get set to default values on file creation regardless.

Additionally, settings should likely not be uberStates? They are not related to the file you're playing on, e.g. should change immediately when you change their value, and allowing seeds to alter accessibility settings also just seems like a bad thing.

**Comment by MunWolf** [comment]
https://github.com/ori-rando/wotw-client/commit/505f1b2d6e2cf2fe5daa40b694cd80f95a67acbc
Fixes settings not being read.

and yes I agree that these should not be an uberstate, Ill probably move it in 2.0 since it will break the save format.

**Comment by MunWolf** [comment]
This was fixed in https://github.com/ori-rando/wotw-client/commit/7c2c285ff26cb4162314b5e7a100f81e9ddbff0b
We no longer save these settings in an uberstate.
