### ISSUE TITLE
No easy way to install a stable version

### ISSUE THREAD

**Issue by Foopyo** [ori-rando/wotw-client#296]
- New users usually ends up installing a beta version (both the build and client repos ends up downloading beta versiosn)
- Users updating from before-launcher-times usually end up updating to a beta

This is especially bad since seedgen is currently not working on the beta version.

**Comment by timoschwarzer** [comment]
This is already fixed on dev by adding a download button.

> Users updating from before-launcher-times usually end up updating to a beta

This has to be fixed by @sparkle-preference, I won't touch AHK oriLol (debatable if we even want to support auto update from 0.x these days.) Should probably just prepare the migration files and open wotw.orirando.com in the browser.
