### ISSUE TITLE
Offline seed getting synced

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-client#304]
When loading an offline seed while in the main menu and then starting a new file, it still syncs all the world states from a previously loaded online seed.

Steps to reproduce
1) Create a new "Normal" game
2) Create a new universe in it
3) Load this seed: [seed.wotwr](https://cdn.discordapp.com/attachments/942484835631521812/1028651808815595560/seed.wotwr)
4) Start a new file, Collect something
5) Exit to menu
6) Load this seed: [empty.wotwr](https://cdn.discordapp.com/attachments/942484835631521812/1028651961978998824/empty.wotwr)
7) Start a new file

**Comment by timoschwarzer** [comment]
Fixed with https://github.com/ori-rando/wotw-client/commit/dccef1769f38a7cf0cc8dba7ad7b1877429aad92
